import { SessionProvider } from "next-auth/react";
import { pretendard } from "./fonts";
import "./globals.css";
import type { Metadata } from "next";
import RQProvider from "@/components/RQProvider";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${pretendard.className} desktop:min-w-[1280px]`}
    >
      <body>
        <SessionProvider>
          <RQProvider>
            {children}
            <Toaster />
          </RQProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
